import type { NextConfig } from "next";
import fs from "fs";
import path from "path";

const nextAuthRootEntry = path.resolve(__dirname, "node_modules/next-auth/index.js");
const nextAuthServerEntry = fs.existsSync(nextAuthRootEntry)
  ? nextAuthRootEntry
  : path.resolve(__dirname, "node_modules/next-auth/next/index.js");

const nextConfig: NextConfig = {
  outputFileTracingRoot: path.resolve(__dirname),
  // Disable isolatedDevBuild so dev mode uses .next/ directly (same as production build).
  // With isolatedDevBuild:true (the default), Next.js uses .next/dev/ as distDir but the
  // directory never gets populated because webpack's afterEmit assets are SizeOnlySource objects
  // that cannot be read back from compilation.assets. Using .next/ directly lets webpack write
  // manifests to real disk paths where the server can find them via readFileSync/require().
  experimental: {
    isolatedDevBuild: false,
  },
  serverExternalPackages: [
    "@prisma/client",
    "@prisma/adapter-pg",
    "@prisma/driver-adapter-utils",
    "@prisma/debug",
    "@prisma/get-platform",
    "@prisma/engines-version",
    "prisma",
    "better-sqlite3",
  ],
  images: {
    qualities: [75, 90],
    remotePatterns: [],
  },
  webpack(config, { dev, isServer }) {
    // Filesystem cache speeds up dev rebuilds. Do not set `buildDependencies.config`
    // to `__filename` here: Next compiles `next.config.ts` to a non-disk
    // `next.config.compiled.js` path, which breaks PackFileCacheStrategy and can
    // stall or confuse incremental compilation.
    if (dev) {
      config.cache = {
        type: "filesystem",
        cacheDirectory: path.resolve(__dirname, ".next-webpack-cache"),
      };
    }

    // Exclude large non-source directories from the webpack watcher to
    // dramatically reduce startup and incremental rebuild time.
    config.watchOptions = {
      ...config.watchOptions,
      ignored: [
        "**/node_modules/**",
        "**/node_modules.nosync/**",
        "**/.git/**",
        "**/lab-report-ocr-api-main/**",
        "**/.next-webpack-cache/**",
      ],
    };

    // Force CJS builds to avoid webpack ESM static-analysis errors:
    // - framer-motion 12.x has ESM circular deps that hang compilation
    // - @prisma/* packages use ESM internally; CJS aliases prevent "Debug is not exported" errors
    const prismaNodeClient = path.resolve(
      __dirname,
      "node_modules/.prisma/client/index.js"
    );
    config.resolve.alias = {
      ...config.resolve.alias,
      "framer-motion": path.resolve(
        __dirname,
        "node_modules/framer-motion/dist/cjs/index.js"
      ),
      "@prisma/debug": path.resolve(
        __dirname,
        "node_modules/@prisma/debug/dist/index.js"
      ),
      "@prisma/driver-adapter-utils": path.resolve(
        __dirname,
        "node_modules/@prisma/driver-adapter-utils/dist/index.js"
      ),
      // Server-only: never resolve @prisma/client to the browser stub (missing model delegates → undefined.findMany).
      // Explicit next-auth entry avoids occasional "Can't resolve 'next-auth'" under webpack + package exports.
      // Use $ (exact match) so the alias doesn't intercept next-auth/react or other subpaths.
      ...(isServer
        ? {
            "@prisma/client$": prismaNodeClient,
            "next-auth$": nextAuthServerEntry,
          }
        : {}),
      // Explicit subpath aliases for next-auth: package exports map isn't always resolved by webpack.
      "next-auth/react": path.resolve(__dirname, "node_modules/next-auth/react/index.js"),
      "next-auth/jwt": path.resolve(__dirname, "node_modules/next-auth/jwt/index.js"),
    };

    // fallback-build-manifest.json is Turbopack-only and never generated by webpack.
    // Write a stub once after the first compilation so loadDefaultErrorComponents() doesn't crash.
    if (dev) {
      config.plugins = [
        ...(config.plugins ?? []),
        {
          apply(compiler: any) {
            compiler.hooks.afterEmit.tap("WriteFallbackBuildManifest", (compilation: any) => {
              const nativeFs = require("fs");
              const nativePath = require("path");
              const outPath: string = compilation.outputOptions?.path ?? "";
              if (!outPath) return;
              const distRoot = outPath.endsWith("/server") || outPath.endsWith("\\server")
                ? nativePath.dirname(outPath)
                : outPath;
              const fbPath = nativePath.join(distRoot, "fallback-build-manifest.json");
              if (!nativeFs.existsSync(fbPath)) {
                try {
                  nativeFs.mkdirSync(distRoot, { recursive: true });
                  nativeFs.writeFileSync(fbPath, '{"pages":{}}');
                } catch {}
              }
            });
          },
        },
      ];
    }

    if (process.env.WEBPACK_PROGRESS === "1") {
      const webpack = require("webpack") as typeof import("webpack");
      let lastPct = -1;
      config.plugins = [
        ...(config.plugins ?? []),
        new webpack.ProgressPlugin((pct, msg, ...args) => {
          const p = Math.floor(pct * 100);
          if (p >= lastPct + 5 || pct >= 1) {
            lastPct = p;
            console.warn(`[webpack] ${p}% ${msg} ${args.filter(Boolean).join(" ")}`);
          }
        }),
      ];
    }

    return config;
  },
};

export default nextConfig;
