import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  outputFileTracingRoot: path.resolve(__dirname),
  // Disable isolatedDevBuild so dev mode uses .next/ directly (same as production build).
  // With isolatedDevBuild:true (the default), Next.js uses .next/dev/ as distDir but the
  // directory never gets populated because webpack's afterEmit assets are SizeOnlySource objects
  // that cannot be read back from compilation.assets. Using .next/ directly lets webpack write
  // manifests to real disk paths where the server can find them via readFileSync/require().
  experimental: {
    isolatedDevBuild: false,
  },
  serverExternalPackages: [
    "@prisma/client",
    "@prisma/adapter-pg",
    "@prisma/driver-adapter-utils",
    "@prisma/debug",
    "@prisma/get-platform",
    "@prisma/engines-version",
    "prisma",
  ],
  images: {
    qualities: [75, 90],
    remotePatterns: [],
  },
  webpack(config, { dev }) {
    // Force CJS builds to avoid webpack ESM static-analysis errors:
    // - framer-motion 12.x has ESM circular deps that hang compilation
    // - @prisma/* packages use ESM internally; CJS aliases prevent "Debug is not exported" errors
    config.resolve.alias = {
      ...config.resolve.alias,
      "framer-motion": path.resolve(
        __dirname,
        "node_modules/framer-motion/dist/cjs/index.js"
      ),
      "@prisma/debug": path.resolve(
        __dirname,
        "node_modules/@prisma/debug/dist/index.js"
      ),
      "@prisma/driver-adapter-utils": path.resolve(
        __dirname,
        "node_modules/@prisma/driver-adapter-utils/dist/index.js"
      ),
    };

    // fallback-build-manifest.json is Turbopack-only and never generated by webpack.
    // Write a stub once after the first compilation so loadDefaultErrorComponents() doesn't crash.
    if (dev) {
      config.plugins = [
        ...(config.plugins ?? []),
        {
          apply(compiler: any) {
            compiler.hooks.afterEmit.tap("WriteFallbackBuildManifest", (compilation: any) => {
              const nativeFs = require("fs");
              const nativePath = require("path");
              const outPath: string = compilation.outputOptions?.path ?? "";
              if (!outPath) return;
              const distRoot = outPath.endsWith("/server") || outPath.endsWith("\\server")
                ? nativePath.dirname(outPath)
                : outPath;
              const fbPath = nativePath.join(distRoot, "fallback-build-manifest.json");
              if (!nativeFs.existsSync(fbPath)) {
                try {
                  nativeFs.mkdirSync(distRoot, { recursive: true });
                  nativeFs.writeFileSync(fbPath, '{"pages":{}}');
                } catch {}
              }
            });
          },
        },
      ];
    }

    return config;
  },
};

export default nextConfig;
