// Seed records for biomarker_coverage_ui_content and biomarker_doctor_script_templates.
// locale = 'de'    → Germany (GKV / PKV system)
// locale = 'en-gb' → United Kingdom (NHS / private healthcare system)
// Source of truth for the UI layer; deterministic rule-based templates.

export type CoverageRecord = {
  locale: string;
  biomarker_name_normalized: string;
  source_biomarker_name: string;
  source_category: string;
  source_sample_type: string;
  gkv_raw_coverage: string;
  pkv_raw_coverage: string;
  gkv_raw_frequency: string;
  gkv_status_label: string;
  gkv_user_text: string;
  gkv_frequency_user_text: string | null;
  gkv_extra_note: string | null;
  pkv_status_label: string;
  pkv_user_text: string;
  pkv_extra_note: string | null;
  self_pay_note: string | null;
};

export type ScriptRecord = {
  locale: string;
  biomarker_name_normalized: string;
  source_biomarker_name: string;
  source_category: string;
  source_sample_type: string;
  intro_template: string;
  symptom_template: string | null;
  coverage_question_template: string | null;
  followup_template: string;
  why_this_matters_template: string;
  private_option_template: string | null;
};

export const COVERAGE_SEED: CoverageRecord[] = [
  {
    locale: "de",
    biomarker_name_normalized: "vitamin_d_25_oh",
    source_biomarker_name: "Vitamin D (25-OH)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional (Symptoms/Deficiency)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "IGeL for routine; Indication required",
    gkv_status_label: "Sometimes covered",
    gkv_user_text: "For GKV, Vitamin D (25-OH) is usually not covered as a routine preventive check. It may be covered when symptoms, suspected deficiency, or a medical indication are documented.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV; medical indication is typically required for reimbursement.",
    gkv_extra_note: "Without a medical indication, this is usually handled as a private / self-paid service.",
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Vitamin D (25-OH) is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: "If you are privately insured, it can still be worth confirming reimbursement with your insurer if you want certainty.",
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "ferritin",
    source_biomarker_name: "Ferritin",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "For GKV, Ferritin may be covered when there is a documented medical indication such as suspected iron deficiency or anaemia.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Ferritin is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "vitamin_b12_cobalamin",
    source_biomarker_name: "Vitamin B12 (Cobalamin)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "For GKV, Vitamin B12 may be covered when there is a documented medical indication such as fatigue, neurological symptoms, or suspected deficiency.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Vitamin B12 is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "tsh_thyroid_stimulating_hormone",
    source_biomarker_name: "TSH (Thyroid Stimulating Hormone)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "For GKV, TSH may be covered when there is a medical indication such as symptoms of thyroid dysfunction, fatigue, or weight changes.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, TSH is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "free_t4_ft4",
    source_biomarker_name: "Free T4 (fT4)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "For GKV, Free T4 may be covered when there is a medical indication, typically alongside TSH when thyroid dysfunction is suspected.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Free T4 is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "total_cholesterol",
    source_biomarker_name: "Total Cholesterol",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Screening)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "Every 3 years from age 35 (Check-up 35)",
    gkv_status_label: "Covered as screening",
    gkv_user_text: "For GKV, a basic lipid check including Total Cholesterol is available within the preventive Check-up 35 screening programme, depending on eligibility.",
    gkv_frequency_user_text: "Available every 3 years from age 35 as part of the GKV preventive check-up.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Total Cholesterol is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "hba1c_glycated_hemoglobin",
    source_biomarker_name: "HbA1c (Glycated Haemoglobin)",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "For GKV, HbA1c may be covered when there is a medical indication such as risk factors for diabetes, elevated fasting glucose, or symptoms suggesting blood sugar instability.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, HbA1c is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "cortisol_morning",
    source_biomarker_name: "Cortisol (Morning)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "IGeL for routine",
    gkv_status_label: "Sometimes covered",
    gkv_user_text: "For GKV, Cortisol is not usually covered as a routine preventive check, but it may be covered depending on symptoms, history, or medical context.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV.",
    gkv_extra_note: "If coverage is unclear, ask whether your symptoms or history provide a medical indication.",
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Cortisol is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "estradiol_e2",
    source_biomarker_name: "Estradiol (E2)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "For GKV, Estradiol may be covered when there is a medical indication such as cycle irregularities, fertility investigation, or perimenopausal symptoms.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Estradiol is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "amh_anti_mullerian_hormone",
    source_biomarker_name: "AMH (Anti-Müllerian Hormone)",
    source_category: "Fertility",
    source_sample_type: "Blood",
    gkv_raw_coverage: "No (IGeL)",
    pkv_raw_coverage: "Varies",
    gkv_raw_frequency: "IGeL for routine",
    gkv_status_label: "Usually self-paid",
    gkv_user_text: "For GKV, AMH is usually handled as a self-paid service (IGeL) unless there is a specific medical reason such as a fertility investigation in an approved context.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV.",
    gkv_extra_note: "Without a medical indication, this is usually handled as a private / self-paid service.",
    pkv_status_label: "Depends on your tariff",
    pkv_user_text: "For PKV, reimbursement for AMH may depend on your tariff, indication, and billing context.",
    pkv_extra_note: "Check your tariff if you want certainty before ordering the test.",
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "dhea_s",
    source_biomarker_name: "DHEA-S",
    source_category: "Hormones",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "IGeL for routine",
    gkv_status_label: "Sometimes covered",
    gkv_user_text: "For GKV, DHEA-S is not usually covered as a routine preventive check, but it may be covered depending on symptoms, history, or medical context.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV.",
    gkv_extra_note: "If coverage is unclear, ask whether your symptoms or history provide a medical indication.",
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, DHEA-S is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "alt_alanine_aminotransferase",
    source_biomarker_name: "ALT (Alanine Aminotransferase)",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Usually covered",
    gkv_user_text: "For GKV, ALT is usually covered when medically appropriate, for example as part of liver function assessment.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, ALT is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "creatinine",
    source_biomarker_name: "Creatinine",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Usually covered",
    gkv_user_text: "For GKV, Creatinine is usually covered when medically appropriate, for example as part of kidney function assessment.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Creatinine is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "hscrp_high_sensitivity_crp",
    source_biomarker_name: "hsCRP (high-sensitivity CRP)",
    source_category: "Inflammation",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "IGeL for routine",
    gkv_status_label: "Sometimes covered",
    gkv_user_text: "For GKV, hsCRP is not usually covered as a routine preventive check, but it may be covered depending on symptoms, history, or medical context.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV.",
    gkv_extra_note: "If coverage is unclear, ask whether your symptoms or history provide a medical indication.",
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, hsCRP is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "omega_3_index",
    source_biomarker_name: "Omega-3 Index",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "No (IGeL)",
    pkv_raw_coverage: "Varies",
    gkv_raw_frequency: "IGeL for routine",
    gkv_status_label: "Usually self-paid",
    gkv_user_text: "For GKV, Omega-3 Index is usually handled as a self-paid service (IGeL) unless there is a specific medical reason.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV.",
    gkv_extra_note: "Without a medical indication, this is usually handled as a private / self-paid service.",
    pkv_status_label: "Depends on your tariff",
    pkv_user_text: "For PKV, reimbursement for Omega-3 Index may depend on your tariff, indication, and billing context.",
    pkv_extra_note: "Check your tariff if you want certainty before ordering the test.",
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "magnesium_serum",
    source_biomarker_name: "Magnesium (serum)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As medically necessary",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "For GKV, Magnesium may be covered when there is a documented medical indication such as muscle cramps, fatigue, or suspected deficiency.",
    gkv_frequency_user_text: "Usually based on medical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Magnesium is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "iodine_urine",
    source_biomarker_name: "Iodine (urine)",
    source_category: "Nutrients",
    source_sample_type: "Urine",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "IGeL for routine",
    gkv_status_label: "Sometimes covered",
    gkv_user_text: "For GKV, Iodine (urine) is not usually covered as a routine preventive check, but it may be covered depending on symptoms, history, or medical context.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV.",
    gkv_extra_note: "If coverage is unclear, ask whether your symptoms or history provide a medical indication.",
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, Iodine is often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "sti_screening_basic",
    source_biomarker_name: "STI Screening (basic)",
    source_category: "Sexual Health",
    source_sample_type: "Blood / Urine",
    gkv_raw_coverage: "Yes (Screening)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "Varies by test and eligibility",
    gkv_status_label: "Covered as screening",
    gkv_user_text: "For GKV, some STI tests are available within preventive screening rules depending on age, eligibility, and the specific test. Ask your gynaecologist or GP.",
    gkv_frequency_user_text: "Availability depends on the specific test and your eligibility criteria.",
    gkv_extra_note: null,
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, STI screening tests are often reimbursed, but the exact coverage depends on your tariff and medical context.",
    pkv_extra_note: null,
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "gut_microbiome_basic",
    source_biomarker_name: "Gut Microbiome (basic)",
    source_category: "Gut Health",
    source_sample_type: "Stool",
    gkv_raw_coverage: "No (IGeL)",
    pkv_raw_coverage: "Varies",
    gkv_raw_frequency: "IGeL for routine",
    gkv_status_label: "Usually self-paid",
    gkv_user_text: "For GKV, gut microbiome testing is usually handled as a self-paid service (IGeL) unless there is a specific medical reason.",
    gkv_frequency_user_text: "Routine use is usually self-paid under GKV.",
    gkv_extra_note: "Without a medical indication, this is usually handled as a private / self-paid service.",
    pkv_status_label: "Depends on your tariff",
    pkv_user_text: "For PKV, reimbursement for gut microbiome testing may depend on your tariff, indication, and billing context.",
    pkv_extra_note: "Check your tariff if you want certainty before ordering the test.",
    self_pay_note: "A private / self-paid route may be possible if the test is not reimbursed in your situation.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "comprehensive_preventive_panel",
    source_biomarker_name: "Comprehensive Preventive Panel",
    source_category: "Preventive",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Varies",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "Depends on context",
    gkv_status_label: "Depends on context",
    gkv_user_text: "For GKV, coverage for a comprehensive preventive panel depends on the medical context and your doctor's indication. Individual components may be covered separately.",
    gkv_frequency_user_text: "Depends on the specific components and your medical context.",
    gkv_extra_note: "If coverage is unclear, ask which components your doctor can include under your current indication.",
    pkv_status_label: "Often covered",
    pkv_user_text: "For PKV, a comprehensive preventive panel is often reimbursed, but the exact coverage depends on your tariff and the components ordered.",
    pkv_extra_note: "If you are privately insured, it can still be worth confirming reimbursement with your insurer if you want certainty.",
    self_pay_note: "If reimbursement is unclear, ask your practice or insurer whether a private / self-paid route is available.",
  },
];

export const SCRIPT_SEED: ScriptRecord[] = [
  {
    locale: "de",
    biomarker_name_normalized: "vitamin_d_25_oh",
    source_biomarker_name: "Vitamin D (25-OH)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether Vitamin D (25-OH) makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my symptoms and history, could Vitamin D be relevant to check now?",
    coverage_question_template: "If Vitamin D is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Vitamin D now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If Vitamin D is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "ferritin",
    source_biomarker_name: "Ferritin",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking Ferritin makes sense in my case — could we include it in my next blood test?",
    symptom_template: "I have been experiencing fatigue and low energy — could Ferritin or iron levels be relevant to check?",
    coverage_question_template: "If Ferritin is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Ferritin now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If Ferritin is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "vitamin_b12_cobalamin",
    source_biomarker_name: "Vitamin B12 (Cobalamin)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether Vitamin B12 makes sense in my case — could we include it in my next blood test?",
    symptom_template: "I have been experiencing fatigue and low energy — could B12 be relevant to check?",
    coverage_question_template: "If B12 is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do B12 now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If B12 is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "tsh_thyroid_stimulating_hormone",
    source_biomarker_name: "TSH (Thyroid Stimulating Hormone)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking TSH makes sense in my case — could we include it in my next blood test?",
    symptom_template: "I have been noticing changes in energy, weight, or mood — could my thyroid be worth checking?",
    coverage_question_template: "If TSH is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do TSH now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "de",
    biomarker_name_normalized: "free_t4_ft4",
    source_biomarker_name: "Free T4 (fT4)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking Free T4 alongside TSH makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my symptoms, could an extended thyroid panel including Free T4 be relevant?",
    coverage_question_template: "If Free T4 is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Free T4 now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "de",
    biomarker_name_normalized: "total_cholesterol",
    source_biomarker_name: "Total Cholesterol",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether a lipid panel including cholesterol makes sense in my case — could we include it in my next check-up?",
    symptom_template: "Given my family history and lifestyle, could checking cholesterol be relevant now?",
    coverage_question_template: "Am I eligible for the preventive Check-up 35 cholesterol check, or is there another route?",
    followup_template: "If we do a lipid panel now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "de",
    biomarker_name_normalized: "hba1c_glycated_hemoglobin",
    source_biomarker_name: "HbA1c (Glycated Haemoglobin)",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking HbA1c makes sense in my case — could we include it in my next blood test?",
    symptom_template: "I have been noticing energy dips and cravings — could blood sugar regulation be worth checking?",
    coverage_question_template: "If HbA1c is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do HbA1c now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If HbA1c is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "cortisol_morning",
    source_biomarker_name: "Cortisol (Morning)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking morning Cortisol makes sense in my case — could we include it in my next blood test?",
    symptom_template: "I have been experiencing persistent fatigue and difficulty managing stress — could cortisol be relevant to check?",
    coverage_question_template: "If Cortisol is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Cortisol now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If Cortisol is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "estradiol_e2",
    source_biomarker_name: "Estradiol (E2)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking Estradiol makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my cycle and symptoms, could hormone levels including Estradiol be relevant to check?",
    coverage_question_template: "If Estradiol is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Estradiol now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "de",
    biomarker_name_normalized: "amh_anti_mullerian_hormone",
    source_biomarker_name: "AMH (Anti-Müllerian Hormone)",
    source_category: "Fertility",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking AMH for ovarian reserve makes sense in my case — could we include it in my next blood test?",
    symptom_template: "I am thinking about my future fertility — could AMH be worth checking now?",
    coverage_question_template: "Is there a covered route for AMH in my situation, or would this be self-paid?",
    followup_template: "If we do AMH now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If AMH is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "dhea_s",
    source_biomarker_name: "DHEA-S",
    source_category: "Hormones",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking DHEA-S makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my energy levels and hormonal symptoms, could DHEA-S be relevant to check?",
    coverage_question_template: "If DHEA-S is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do DHEA-S now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If DHEA-S is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "alt_alanine_aminotransferase",
    source_biomarker_name: "ALT (Alanine Aminotransferase)",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking liver function including ALT makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my history and current medications, could liver function be worth checking?",
    coverage_question_template: "If ALT is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do ALT now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "de",
    biomarker_name_normalized: "creatinine",
    source_biomarker_name: "Creatinine",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking kidney function including Creatinine makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my history and current medications, could kidney function be worth checking?",
    coverage_question_template: "If Creatinine is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Creatinine now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "de",
    biomarker_name_normalized: "hscrp_high_sensitivity_crp",
    source_biomarker_name: "hsCRP (high-sensitivity CRP)",
    source_category: "Inflammation",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking hsCRP for low-grade inflammation makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my symptoms and history, could checking inflammatory markers be relevant now?",
    coverage_question_template: "If hsCRP is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do hsCRP now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If hsCRP is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "omega_3_index",
    source_biomarker_name: "Omega-3 Index",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking my Omega-3 Index makes sense in my case — could we include it in my next blood test?",
    symptom_template: "Based on my diet and cardiovascular risk factors, could checking Omega-3 levels be relevant?",
    coverage_question_template: "Is there a covered route for Omega-3 Index in my situation, or would this be self-paid?",
    followup_template: "If we do Omega-3 Index now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If Omega-3 Index is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "magnesium_serum",
    source_biomarker_name: "Magnesium (serum)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking Magnesium makes sense in my case — could we include it in my next blood test?",
    symptom_template: "I have been experiencing muscle cramps and sleep difficulties — could Magnesium be relevant to check?",
    coverage_question_template: "If Magnesium is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Magnesium now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If Magnesium is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "iodine_urine",
    source_biomarker_name: "Iodine (urine)",
    source_category: "Nutrients",
    source_sample_type: "Urine",
    intro_template: "I would like to discuss whether checking Iodine status makes sense in my case — could we include it in my next urine test?",
    symptom_template: "Based on my thyroid history and diet, could Iodine be relevant to check?",
    coverage_question_template: "If Iodine testing is not routinely covered, can you tell me whether there is a medical indication in my case?",
    followup_template: "If we do Iodine now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If Iodine testing is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "sti_screening_basic",
    source_biomarker_name: "STI Screening (basic)",
    source_category: "Sexual Health",
    source_sample_type: "Blood / Urine",
    intro_template: "I would like to discuss whether an STI screening makes sense in my case — could we include relevant tests in my next appointment?",
    symptom_template: "Based on my history and circumstances, could an STI screen be appropriate?",
    coverage_question_template: "Which STI tests would be covered in my situation, and are there any eligibility criteria I should know about?",
    followup_template: "How often do you recommend STI screening for someone with my profile?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "de",
    biomarker_name_normalized: "gut_microbiome_basic",
    source_biomarker_name: "Gut Microbiome (basic)",
    source_category: "Gut Health",
    source_sample_type: "Stool",
    intro_template: "I would like to discuss whether gut microbiome testing makes sense in my case — is this something we could explore?",
    symptom_template: "I have been experiencing digestive symptoms — could gut microbiome testing be relevant?",
    coverage_question_template: "Is there a covered route for gut microbiome testing in my situation, or would this be self-paid?",
    followup_template: "If we do gut microbiome testing now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If gut microbiome testing is not reimbursed in your situation, you can ask whether there is a private / self-paid option.",
  },
  {
    locale: "de",
    biomarker_name_normalized: "comprehensive_preventive_panel",
    source_biomarker_name: "Comprehensive Preventive Panel",
    source_category: "Preventive",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss a more comprehensive preventive blood panel — which components could we include in my next test?",
    symptom_template: "Given my current symptoms and profile, could a broader preventive check be relevant now?",
    coverage_question_template: "Which components of a comprehensive preventive panel would be covered in my situation, and which might be self-paid?",
    followup_template: "How often do you recommend a comprehensive preventive check for someone with my profile?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If some components are not reimbursed, you can ask whether a private / self-paid option is available for those specific tests.",
  },
];

// ─── UK (NHS / Private) ───────────────────────────────────────────────────────
// gkv_* fields map to NHS context; pkv_* fields map to private healthcare context.
// Field naming is shared with the DE records for simplicity.

const UK_COVERAGE: CoverageRecord[] = [
  {
    locale: "en-gb",
    biomarker_name_normalized: "vitamin_d_25_oh",
    source_biomarker_name: "Vitamin D (25-OH)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Sometimes on NHS",
    gkv_user_text: "On the NHS, Vitamin D testing is not offered routinely. Your GP may arrange it if you have symptoms of deficiency, are in a high-risk group, or have a clinical reason documented.",
    gkv_frequency_user_text: "Usually only arranged when clinically indicated, not as a routine annual check.",
    gkv_extra_note: "Groups at higher risk of deficiency (e.g. limited sun exposure, darker skin, certain conditions) may find it easier to get a referral.",
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, Vitamin D testing is widely available without a clinical indication.",
    pkv_extra_note: "Private tests are typically available online or at walk-in labs, often without a GP appointment.",
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "ferritin",
    source_biomarker_name: "Ferritin",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "On the NHS, Ferritin is typically included in a full blood count or iron studies when your GP suspects anaemia, iron deficiency, or you report fatigue and related symptoms.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, Ferritin is widely available as part of iron panels or standalone tests.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "vitamin_b12_cobalamin",
    source_biomarker_name: "Vitamin B12 (Cobalamin)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "On the NHS, B12 is commonly tested when a GP investigates fatigue, neurological symptoms, or suspected deficiency — particularly in people with absorption issues or dietary restrictions.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, B12 testing is widely available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "tsh_thyroid_stimulating_hormone",
    source_biomarker_name: "TSH (Thyroid Stimulating Hormone)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "On the NHS, TSH is typically tested when your GP suspects thyroid dysfunction based on symptoms such as fatigue, weight changes, mood shifts, or temperature sensitivity.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, TSH testing is widely available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "free_t4_ft4",
    source_biomarker_name: "Free T4 (fT4)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "On the NHS, Free T4 is usually measured alongside TSH when thyroid dysfunction is being investigated, typically as part of a thyroid function panel.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, Free T4 is widely available as part of thyroid panels.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "total_cholesterol",
    source_biomarker_name: "Total Cholesterol",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Screening)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "Every 5 years from age 40 (NHS Health Check)",
    gkv_status_label: "Available as NHS screening",
    gkv_user_text: "On the NHS, cholesterol is included in the NHS Health Check offered to adults aged 40–74 every 5 years. It may also be arranged earlier if you have cardiovascular risk factors.",
    gkv_frequency_user_text: "Offered as part of the NHS Health Check every 5 years from age 40.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, cholesterol panels are widely available without waiting for an NHS Health Check.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "hba1c_glycated_hemoglobin",
    source_biomarker_name: "HbA1c (Glycated Haemoglobin)",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "On the NHS, HbA1c is tested when your GP suspects diabetes or pre-diabetes, or when you have risk factors such as obesity, family history, or polycystic ovaries.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, HbA1c testing is widely available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "cortisol_morning",
    source_biomarker_name: "Cortisol (Morning)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Usually specialist-referred",
    gkv_user_text: "On the NHS, morning cortisol testing is not usually arranged by a GP as a routine check. It is more commonly ordered following a specialist (endocrinology) referral when adrenal or cortisol dysregulation is suspected.",
    gkv_frequency_user_text: "Usually arranged following a specialist referral rather than as a routine check.",
    gkv_extra_note: "If you have persistent fatigue, low blood pressure, or other signs of adrenal dysfunction, ask your GP whether a specialist referral may be appropriate.",
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, morning cortisol testing is available without a specialist referral.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "estradiol_e2",
    source_biomarker_name: "Estradiol (E2)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "On the NHS, Estradiol may be tested when investigating cycle irregularities, perimenopausal symptoms, or fertility concerns. It is commonly arranged by a GP or gynaecologist.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, Estradiol testing is widely available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "amh_anti_mullerian_hormone",
    source_biomarker_name: "AMH (Anti-Müllerian Hormone)",
    source_category: "Fertility",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Usually via fertility referral",
    gkv_user_text: "On the NHS, AMH is not available as a routine GP test. It is typically measured as part of a fertility investigation following a referral to a fertility or gynaecology clinic.",
    gkv_frequency_user_text: "Usually only available through a fertility or gynaecology referral.",
    gkv_extra_note: "If you are considering future fertility planning, ask your GP whether a referral is appropriate.",
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or fertility clinic, AMH testing is widely available and does not require a referral.",
    pkv_extra_note: "This is one of the most commonly requested private reproductive health tests.",
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "dhea_s",
    source_biomarker_name: "DHEA-S",
    source_category: "Hormones",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Usually specialist-referred",
    gkv_user_text: "On the NHS, DHEA-S testing is not routinely available from a GP. It is usually ordered following a specialist referral for suspected adrenal or androgen-related conditions.",
    gkv_frequency_user_text: "Usually arranged following a specialist referral rather than as a routine check.",
    gkv_extra_note: "If you have symptoms suggesting androgen excess or adrenal dysfunction, ask your GP whether a referral may be appropriate.",
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, DHEA-S testing is available without a specialist referral.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "alt_alanine_aminotransferase",
    source_biomarker_name: "ALT (Alanine Aminotransferase)",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Usually covered by NHS",
    gkv_user_text: "On the NHS, ALT is a standard liver function test that your GP can arrange when investigating liver health, medication effects, or general health screening.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, liver function tests including ALT are widely available.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "creatinine",
    source_biomarker_name: "Creatinine",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Usually covered by NHS",
    gkv_user_text: "On the NHS, Creatinine is part of urea and electrolytes (U&E), a standard kidney function test your GP can arrange for general health checks or when monitoring certain medications.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, kidney function tests including Creatinine are widely available.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "hscrp_high_sensitivity_crp",
    source_biomarker_name: "hsCRP (high-sensitivity CRP)",
    source_category: "Inflammation",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Sometimes on NHS",
    gkv_user_text: "On the NHS, standard CRP (not high-sensitivity) is more commonly used to assess acute inflammation. High-sensitivity CRP for cardiovascular risk assessment is less routinely available but may be arranged in some contexts.",
    gkv_frequency_user_text: "Usually only arranged when clinically indicated.",
    gkv_extra_note: "If you want a high-sensitivity result specifically, it is worth mentioning this when speaking with your GP.",
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, high-sensitivity CRP is widely available as a standalone test.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "omega_3_index",
    source_biomarker_name: "Omega-3 Index",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "No",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "Not a routine NHS test",
    gkv_status_label: "Not available on NHS",
    gkv_user_text: "Omega-3 Index testing is not a routine NHS test and is not typically available through a GP referral. It is almost exclusively available through private or self-pay routes.",
    gkv_frequency_user_text: null,
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, Omega-3 Index testing is available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "A private or self-pay test is the main route for Omega-3 Index in the UK.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "magnesium_serum",
    source_biomarker_name: "Magnesium (serum)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Yes (Indication)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Covered with indication",
    gkv_user_text: "On the NHS, serum Magnesium can be arranged by your GP when investigating muscle cramps, fatigue, or suspected deficiency — particularly in people taking diuretics or with certain conditions.",
    gkv_frequency_user_text: "Usually based on clinical need rather than a fixed routine interval.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, Magnesium testing is widely available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "iodine_urine",
    source_biomarker_name: "Iodine (urine)",
    source_category: "Nutrients",
    source_sample_type: "Urine",
    gkv_raw_coverage: "Conditional",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated",
    gkv_status_label: "Sometimes on NHS",
    gkv_user_text: "On the NHS, urine Iodine testing is not routinely available and is usually only considered in specialist contexts. A GP may refer you if there is a clinical reason.",
    gkv_frequency_user_text: "Usually only arranged following a specialist referral.",
    gkv_extra_note: "Iodine deficiency is uncommon in the UK, but risk may be higher with certain diets (e.g. avoiding all dairy and seafood).",
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, Iodine testing is available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "sti_screening_basic",
    source_biomarker_name: "STI Screening (basic)",
    source_category: "Sexual Health",
    source_sample_type: "Blood / Urine",
    gkv_raw_coverage: "Yes (Screening)",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "As clinically indicated or via sexual health services",
    gkv_status_label: "Available on NHS",
    gkv_user_text: "On the NHS, STI screening is available free of charge through sexual health clinics (GUM clinics) or your GP. Some home testing kits are also available through local authorities.",
    gkv_frequency_user_text: "Available on request at sexual health clinics, often without an appointment.",
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay clinic, STI screening is available with faster turnaround and broader panels.",
    pkv_extra_note: null,
    self_pay_note: "If the NHS route is unavailable, a private or self-pay test is a straightforward option.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "gut_microbiome_basic",
    source_biomarker_name: "Gut Microbiome (basic)",
    source_category: "Gut Health",
    source_sample_type: "Stool",
    gkv_raw_coverage: "No",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "Not a routine NHS test",
    gkv_status_label: "Not available on NHS",
    gkv_user_text: "Gut microbiome profiling is not a routine NHS test and is not available through a GP referral in standard practice. It is exclusively available through private or self-pay routes.",
    gkv_frequency_user_text: null,
    gkv_extra_note: null,
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private laboratory or direct-to-consumer service, gut microbiome testing is available without a clinical indication.",
    pkv_extra_note: null,
    self_pay_note: "A private or self-pay test is the main route for gut microbiome profiling in the UK.",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "comprehensive_preventive_panel",
    source_biomarker_name: "Comprehensive Preventive Panel",
    source_category: "Preventive",
    source_sample_type: "Blood",
    gkv_raw_coverage: "Varies",
    pkv_raw_coverage: "Yes",
    gkv_raw_frequency: "Depends on components and clinical context",
    gkv_status_label: "Partially available on NHS",
    gkv_user_text: "On the NHS, individual components of a comprehensive panel may be available when clinically indicated. The NHS Health Check (ages 40–74) covers some preventive markers. Not all components are routinely available together.",
    gkv_frequency_user_text: "NHS Health Check is offered every 5 years for eligible adults aged 40–74.",
    gkv_extra_note: "Ask your GP which components can be included in your next health review.",
    pkv_status_label: "Routinely available",
    pkv_user_text: "Through a private GP or self-pay laboratory, comprehensive preventive blood panels are widely available and can be customised to your profile.",
    pkv_extra_note: null,
    self_pay_note: "For components not available on the NHS, a private or self-pay test is a straightforward option.",
  },
];

const UK_SCRIPTS: ScriptRecord[] = [
  {
    locale: "en-gb",
    biomarker_name_normalized: "vitamin_d_25_oh",
    source_biomarker_name: "Vitamin D (25-OH)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking my Vitamin D level makes sense — could we include it in my next blood test?",
    symptom_template: "I have been feeling more tired than usual and I get limited sun exposure — could Vitamin D be worth checking?",
    coverage_question_template: "I understand it may not be routine on the NHS — is there a clinical reason in my case that would support getting it done?",
    followup_template: "If we check Vitamin D now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If it is not available through my GP, is there a straightforward private or self-pay option you would recommend?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "ferritin",
    source_biomarker_name: "Ferritin",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking Ferritin or iron levels makes sense — could we include it in my next blood test?",
    symptom_template: "I have been experiencing fatigue and low energy — could iron or Ferritin levels be relevant to check?",
    coverage_question_template: "Would checking Ferritin be possible alongside a full blood count?",
    followup_template: "If we check Ferritin now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "vitamin_b12_cobalamin",
    source_biomarker_name: "Vitamin B12 (Cobalamin)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking B12 makes sense — could we include it in my next blood test?",
    symptom_template: "I have been experiencing fatigue and some difficulty concentrating — could B12 be relevant to check?",
    coverage_question_template: "Would checking B12 be possible as part of my bloods?",
    followup_template: "If we check B12 now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "tsh_thyroid_stimulating_hormone",
    source_biomarker_name: "TSH (Thyroid Stimulating Hormone)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether a thyroid function test makes sense — could we include TSH in my next blood test?",
    symptom_template: "I have been noticing changes in energy, weight, and mood — could my thyroid be worth checking?",
    coverage_question_template: "Would a thyroid function test be something you could arrange based on my symptoms?",
    followup_template: "If we check TSH now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "free_t4_ft4",
    source_biomarker_name: "Free T4 (fT4)",
    source_category: "Thyroid",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether an extended thyroid panel including Free T4 makes sense — could we arrange this?",
    symptom_template: "Based on my symptoms, could an extended thyroid panel including Free T4 be relevant?",
    coverage_question_template: "Would it be possible to include Free T4 alongside TSH in my thyroid panel?",
    followup_template: "If we check Free T4 now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "total_cholesterol",
    source_biomarker_name: "Total Cholesterol",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether a cholesterol check makes sense — could we include a lipid panel in my next blood test?",
    symptom_template: "Given my family history and lifestyle, could checking cholesterol be relevant now?",
    coverage_question_template: "Am I eligible for an NHS Health Check, or is there another route to get a cholesterol check?",
    followup_template: "If we do a cholesterol check now, when would you usually consider repeating it?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "hba1c_glycated_hemoglobin",
    source_biomarker_name: "HbA1c (Glycated Haemoglobin)",
    source_category: "Metabolic",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking HbA1c for blood sugar regulation makes sense — could we include it in my next blood test?",
    symptom_template: "I have been noticing energy dips and cravings — could blood sugar be worth checking?",
    coverage_question_template: "Based on my profile and risk factors, would an HbA1c check be something you could arrange?",
    followup_template: "If we check HbA1c now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If it is not available through my GP, is there a private or self-pay option you would recommend?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "cortisol_morning",
    source_biomarker_name: "Cortisol (Morning)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking morning Cortisol makes sense in my case — could we explore this?",
    symptom_template: "I have been experiencing persistent fatigue and difficulty managing stress — could cortisol be relevant to investigate?",
    coverage_question_template: "Would this require a specialist referral, or is it something a GP can arrange?",
    followup_template: "If we check Cortisol now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If a GP referral is not possible, is there a private route you would recommend?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "estradiol_e2",
    source_biomarker_name: "Estradiol (E2)",
    source_category: "Hormones",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking Estradiol makes sense — could we include it in my next blood test?",
    symptom_template: "Based on my cycle and hormonal symptoms, could checking Estradiol be relevant?",
    coverage_question_template: "Is an Estradiol test something you could arrange based on my symptoms?",
    followup_template: "If we check Estradiol now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "amh_anti_mullerian_hormone",
    source_biomarker_name: "AMH (Anti-Müllerian Hormone)",
    source_category: "Fertility",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss checking AMH for ovarian reserve — could we explore this together?",
    symptom_template: "I am thinking about my future fertility — could AMH be worth checking now?",
    coverage_question_template: "Would I need a fertility clinic referral for AMH on the NHS, or is there another route?",
    followup_template: "If we check AMH now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If a referral is not possible, is there a private fertility clinic or lab you would recommend?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "dhea_s",
    source_biomarker_name: "DHEA-S",
    source_category: "Hormones",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking DHEA-S makes sense — could we explore this?",
    symptom_template: "Based on my energy levels and hormonal symptoms, could DHEA-S be relevant to investigate?",
    coverage_question_template: "Would this require a specialist referral, or is it something a GP can arrange?",
    followup_template: "If we check DHEA-S now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If a GP referral is not possible, is there a private route you would recommend?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "alt_alanine_aminotransferase",
    source_biomarker_name: "ALT (Alanine Aminotransferase)",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether a liver function test makes sense — could we include ALT in my next bloods?",
    symptom_template: "Based on my history and current medications, could liver function be worth checking?",
    coverage_question_template: "Would a liver function test be something you could arrange?",
    followup_template: "If we check liver function now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "creatinine",
    source_biomarker_name: "Creatinine",
    source_category: "Organ Function",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether a kidney function test makes sense — could we include Creatinine in my next bloods?",
    symptom_template: "Based on my history and current medications, could kidney function be worth checking?",
    coverage_question_template: "Would a kidney function test (U&E) be something you could arrange?",
    followup_template: "If we check kidney function now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "hscrp_high_sensitivity_crp",
    source_biomarker_name: "hsCRP (high-sensitivity CRP)",
    source_category: "Inflammation",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking high-sensitivity CRP for inflammation makes sense — could we include it in my next blood test?",
    symptom_template: "Based on my symptoms and history, could checking inflammatory markers be relevant?",
    coverage_question_template: "Is high-sensitivity CRP something that can be arranged through the NHS, or is this more of a private test?",
    followup_template: "If we check hsCRP now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If it is not available through my GP, is there a straightforward private or self-pay option?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "omega_3_index",
    source_biomarker_name: "Omega-3 Index",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to check my Omega-3 Index — I understand this is not usually available on the NHS. Could you advise on the best route?",
    symptom_template: "Based on my diet and cardiovascular risk factors, could checking Omega-3 levels be relevant?",
    coverage_question_template: "Is there any NHS route for Omega-3 Index, or is this exclusively a private test?",
    followup_template: "If I check Omega-3 Index now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "Which private lab or service would you recommend for Omega-3 Index testing?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "magnesium_serum",
    source_biomarker_name: "Magnesium (serum)",
    source_category: "Nutrients",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss whether checking Magnesium makes sense — could we include it in my next blood test?",
    symptom_template: "I have been experiencing muscle cramps and sleep difficulties — could Magnesium be relevant to check?",
    coverage_question_template: "Is serum Magnesium something that can be arranged through the NHS based on my symptoms?",
    followup_template: "If we check Magnesium now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If it is not available through my GP, is there a private or self-pay option you would recommend?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "iodine_urine",
    source_biomarker_name: "Iodine (urine)",
    source_category: "Nutrients",
    source_sample_type: "Urine",
    intro_template: "I would like to discuss whether checking Iodine status makes sense — could we explore this?",
    symptom_template: "Based on my diet (limited dairy and seafood) and thyroid history, could Iodine be relevant to check?",
    coverage_question_template: "Is Iodine testing something that can be arranged through the NHS, or would this be a private test?",
    followup_template: "If we check Iodine now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "If it is not available through my GP, is there a private or self-pay option you would recommend?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "sti_screening_basic",
    source_biomarker_name: "STI Screening (basic)",
    source_category: "Sexual Health",
    source_sample_type: "Blood / Urine",
    intro_template: "I would like to discuss whether an STI screen is appropriate — could we arrange this or could you direct me to the right service?",
    symptom_template: "Based on my circumstances, could an STI screen be appropriate?",
    coverage_question_template: "Is there a sexual health clinic or NHS service you would recommend for STI screening?",
    followup_template: "How often do you recommend STI screening for someone with my profile?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: null,
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "gut_microbiome_basic",
    source_biomarker_name: "Gut Microbiome (basic)",
    source_category: "Gut Health",
    source_sample_type: "Stool",
    intro_template: "I would like to discuss gut microbiome testing — I understand this is not a routine NHS test. Could you advise on the best route?",
    symptom_template: "I have been experiencing digestive symptoms — could gut microbiome testing be relevant?",
    coverage_question_template: "Is there any NHS route for gut microbiome testing, or would this be exclusively through a private service?",
    followup_template: "If I do gut microbiome testing now, when would you usually consider retesting?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "Which private laboratory or service would you recommend for gut microbiome profiling?",
  },
  {
    locale: "en-gb",
    biomarker_name_normalized: "comprehensive_preventive_panel",
    source_biomarker_name: "Comprehensive Preventive Panel",
    source_category: "Preventive",
    source_sample_type: "Blood",
    intro_template: "I would like to discuss a more comprehensive preventive blood panel — which components could we include through the NHS?",
    symptom_template: "Given my current symptoms and profile, could a broader preventive check be relevant now?",
    coverage_question_template: "Am I eligible for an NHS Health Check, or could we arrange individual components as part of my care?",
    followup_template: "How often do you recommend a comprehensive preventive review for someone with my profile?",
    why_this_matters_template: "This may be relevant for you now based on your profile, symptoms, and last known checks. Your profile signals suggest this area is worth reviewing.",
    private_option_template: "For components not available on the NHS, which private lab or service would you recommend?",
  },
];

export const COVERAGE_SEED_UK = UK_COVERAGE;
export const SCRIPT_SEED_UK = UK_SCRIPTS;
