"""
Article processing worker: raw_medical_articles → LLM extraction → blog Article (with sections).
Pipeline: scraper adds to DB → this worker sends to LLM with prompts → creates Article (draft)
with exact blog structure (Context, Why this is trending, etc.) → admin approves by publishing.
"""
from __future__ import annotations

import json
import logging
import re
import sys
from pathlib import Path

# Project root on path for services, config, prompts
_root = Path(__file__).resolve().parent.parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from workers.db import get_conn
from workers.pipeline_logger import (
    log_event,
    EVENT_LLM_FAILURE,
    EVENT_JSON_PARSE_ERROR,
    EVENT_DUPLICATE_ARTICLE,
)
from workers.medical_filter import apply_medical_filter

logger = logging.getLogger(__name__)

PROMPTS_DIR = _root / "prompts"
EXTRACTION_PROMPT_PATH = PROMPTS_DIR / "article_extraction_prompt.txt"
BLOG_ARTICLE_PROMPT_PATH = PROMPTS_DIR / "blog_article_from_research_prompt.txt"
ACTION_PROTOCOL_TRACKING_PROMPT_PATH = PROMPTS_DIR / "action_protocol_and_tracking_prompt.txt"

SECTION_TITLES = [
    "Context",
    "Why this is trending",
    "What research says",
    "What this means for women",
    "When it might apply",
    "When it might not",
    "Implementation considerations",
]
# Sections 8 and 9: generated by action_protocol_and_tracking_prompt
SECTION_8_TITLE = "Action protocol"
SECTION_9_TITLE = "Tracking framework"

VALID_TAG_TYPES = {
    "lifeStage", "symptom", "bodySystem", "preventiveFocus", "trending",
    "biomarker", "hormone", "goal", "rootCause", "interventionType",
    "evidenceLevel", "contentAccess",
}


def _load_prompt(path: Path, fallback: str = "", **kwargs: str) -> str:
    text = path.read_text() if path.exists() else fallback
    for k, v in kwargs.items():
        text = text.replace("{{" + k + "}}", str(v or ""))
    return text


def _slugify(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "article"
    return s[:80]


def _ensure_unique_slug(cur, base_slug: str) -> str:
    slug = base_slug
    n = 0
    while True:
        cur.execute('SELECT id FROM "Article" WHERE slug = %s', (slug,))
        if cur.fetchone() is None:
            return slug
        n += 1
        slug = f"{base_slug}-{n}"[:90]


def _get_or_create_tag_id(cur, slug: str, label: str, tag_type: str) -> int | None:
    if tag_type not in VALID_TAG_TYPES:
        tag_type = "trending"
    cur.execute('SELECT id FROM "TaxonomyTag" WHERE slug = %s', (slug,))
    row = cur.fetchone()
    if row:
        return row[0]
    try:
        cur.execute(
            'INSERT INTO "TaxonomyTag" (slug, label, type) VALUES (%s, %s, %s::"TaxonomyType") RETURNING id',
            (slug, label, tag_type),
        )
        return cur.fetchone()[0]
    except Exception:
        return None


def _create_blog_article_from_llm(cur, raw_id, payload: dict) -> int | None:
    """Insert Article + sections + sources + tag joins. Returns article id or None."""
    title = (payload.get("title") or "Untitled").strip()[:500]
    excerpt = (payload.get("excerpt") or "").strip()[:2000]
    evidence_level = (payload.get("evidenceLevel") or "observational").strip()[:100]
    category = (payload.get("category") or "").strip()[:200] or None
    pillar = (payload.get("pillar") or "Foundations").strip()[:100] or None

    base_slug = _slugify(title)
    slug = _ensure_unique_slug(cur, base_slug)

    cur.execute(
        """
        INSERT INTO "Article" (slug, title, excerpt, pillar, category, "evidenceLevel", "isPublished", "rawArticleId", "createdAt", "updatedAt")
        VALUES (%s, %s, %s, %s, %s, %s, false, %s, NOW(), NOW())
        RETURNING id
        """,
        (slug, title, excerpt, pillar, category, evidence_level, raw_id),
    )
    row = cur.fetchone()
    if not row:
        return None
    article_id = row[0]

    sections = payload.get("sections") or []
    for s in sections:
        idx = s.get("sectionIndex")
        if idx is None or idx < 1 or idx > 7:
            continue
        stitle = (s.get("title") or SECTION_TITLES[idx - 1])[:200]
        body = (s.get("body") or "").strip()[:50000]
        is_gated = bool(s.get("isGated"))
        preview = (s.get("preview") or "").strip()[:500] if is_gated else None
        cur.execute(
            """
            INSERT INTO "ArticleSection" ("articleId", "sectionIndex", title, body, "isGated", preview, "createdAt", "updatedAt")
            VALUES (%s, %s, %s, %s, %s, %s, NOW(), NOW())
            """,
            (article_id, idx, stitle, body or "(No content)", is_gated, preview),
        )

    # Always create sections 8 and 9 (Action protocol, Tracking framework) as placeholders; worker fills them later
    for section_index, stitle in [(8, SECTION_8_TITLE), (9, SECTION_9_TITLE)]:
        cur.execute(
            """
            INSERT INTO "ArticleSection" ("articleId", "sectionIndex", title, body, "isGated", preview, "createdAt", "updatedAt")
            VALUES (%s, %s, %s, %s, true, %s, NOW(), NOW())
            """,
            (article_id, section_index, stitle, "Content will be generated.", "Subscriber-only content."),
        )

    for src in payload.get("sources") or []:
        label = (src.get("label") or "Source").strip()[:500]
        url = (src.get("url") or "").strip()[:2000] or None
        note = (src.get("evidenceNote") or "").strip()[:1000] or None
        cur.execute(
            'INSERT INTO "ArticleSource" ("articleId", label, url, "evidenceNote", "createdAt") VALUES (%s, %s, %s, %s, NOW())',
            (article_id, label, url, note),
        )

    seen_tag_ids = set()
    for t in payload.get("tags") or []:
        slug_t = (t.get("slug") or "").strip()[:100] or "tag"
        label_t = (t.get("label") or slug_t).strip()[:200]
        type_t = (t.get("type") or "trending").strip()
        tag_id = _get_or_create_tag_id(cur, slug_t, label_t, type_t)
        if tag_id and tag_id not in seen_tag_ids:
            seen_tag_ids.add(tag_id)
            try:
                cur.execute('INSERT INTO "ArticleTagJoin" ("articleId", "tagId") VALUES (%s, %s) ON CONFLICT DO NOTHING', (article_id, tag_id))
            except Exception:
                pass

    return article_id


def _preview_text(body: str, max_len: int = 300) -> str:
    """First line or first max_len chars for gated section preview."""
    if not body or not body.strip():
        return "Subscriber-only content."
    first_line = body.strip().split("\n")[0].strip()
    if len(first_line) <= max_len:
        return first_line
    return first_line[: max_len - 3].rstrip() + "..."


def _update_action_and_tracking_sections(
    cur, article_id: int, action_protocol_body: str, tracking_framework_body: str
) -> None:
    """Update existing ArticleSection rows for sectionIndex 8 and 9 with LLM-generated content."""
    for section_index, title, body in [
        (8, SECTION_8_TITLE, (action_protocol_body or "").strip()[:50000] or "(No content)"),
        (9, SECTION_9_TITLE, (tracking_framework_body or "").strip()[:50000] or "(No content)"),
    ]:
        preview = _preview_text(body)
        cur.execute(
            """
            UPDATE "ArticleSection"
            SET title = %s, body = %s, preview = %s, "updatedAt" = NOW()
            WHERE "articleId" = %s AND "sectionIndex" = %s
            """,
            (title, body, preview, article_id, section_index),
        )


def process_unprocessed_articles(limit: int = 10) -> int:
    """
    For each unprocessed raw_medical_article: run extraction LLM → blog-article LLM → create Article (draft) + sections + sources + tags.
    """
    from services.llm_service import generate_completion
    from services.llm_validation import validate_llm_output, ArticleExtractionSchema

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, source, "sourceUrl", title, authors, journal, "publicationDate",
                       abstract, "fullText", keywords, doi
                FROM raw_medical_articles
                WHERE processed = false
                ORDER BY "scrapedAt" ASC
                LIMIT %s
                """,
                (limit,),
            )
            rows = cur.fetchall()
            colnames = [d[0] for d in cur.description]
            articles = [dict(zip(colnames, row)) for row in rows]

    processed_count = 0
    for raw in articles:
        raw_id = raw["id"]
        title = raw["title"] or ""
        abstract = (raw["abstract"] or "")[:12000]
        full_text = (raw["fullText"] or "")[:8000]
        journal = raw["journal"] or ""

        # --- Step 1: Extraction (structured fields from research) ---
        extraction_template = EXTRACTION_PROMPT_PATH.read_text() if EXTRACTION_PROMPT_PATH.exists() else ""
        prompt = _load_prompt(
            EXTRACTION_PROMPT_PATH,
            fallback=extraction_template,
            title=title,
            abstract=abstract,
            full_text=full_text or "(not available)",
            journal=journal,
        )
        try:
            response = generate_completion(prompt)
            response_str = json.dumps(response) if isinstance(response, dict) else str(response)
        except Exception as e:
            log_event(EVENT_LLM_FAILURE, str(e), {"raw_article_id": str(raw_id), "stage": "extraction"})
            logger.exception("LLM extraction failed for %s", raw_id)
            continue

        validated = validate_llm_output(
            response_str,
            retry_with_correction=lambda p: generate_completion(p),
        )
        if validated is None:
            log_event(EVENT_JSON_PARSE_ERROR, "Extraction output invalid", {"raw_article_id": str(raw_id)})
            continue

        summary = validated.summary or ""
        key_findings_str = ", ".join(validated.key_findings[:10]) if validated.key_findings else ""
        biological_systems_str = ", ".join(validated.biological_systems[:10]) if validated.biological_systems else ""
        symptoms_str = ", ".join(validated.symptoms[:10]) if validated.symptoms else ""
        biomarkers_str = ", ".join(validated.biomarkers[:10]) if validated.biomarkers else ""
        root_causes_str = ", ".join(validated.root_causes[:10]) if validated.root_causes else ""
        evidence_level_str = validated.evidence_level or "observational"

        # --- Step 2: Blog article (full structure for blog page) ---
        blog_template = BLOG_ARTICLE_PROMPT_PATH.read_text() if BLOG_ARTICLE_PROMPT_PATH.exists() else ""
        blog_prompt = _load_prompt(
            BLOG_ARTICLE_PROMPT_PATH,
            fallback=blog_template,
            title=title,
            summary=summary,
            key_findings=key_findings_str,
            biological_systems=biological_systems_str,
            symptoms=symptoms_str,
            biomarkers=biomarkers_str,
            root_causes=root_causes_str,
            evidence_level=evidence_level_str,
            abstract=(abstract or "")[:1500],
        )
        try:
            blog_response = generate_completion(blog_prompt)
            if isinstance(blog_response, dict):
                blog_obj = blog_response
            else:
                blog_obj = json.loads(blog_response)
        except Exception as e:
            log_event(EVENT_LLM_FAILURE, str(e), {"raw_article_id": str(raw_id), "stage": "blog_article"})
            logger.exception("Blog article LLM failed for %s", raw_id)
            continue

        if not isinstance(blog_obj, dict):
            log_event(EVENT_JSON_PARSE_ERROR, "Blog article output not a dict", {"raw_article_id": str(raw_id)})
            continue

        # Apply medical filter to section bodies
        for s in blog_obj.get("sections") or []:
            if s.get("body"):
                s["body"] = apply_medical_filter(s["body"])

        try:
            with get_conn() as conn:
                with conn.cursor() as cur:
                    article_id = _create_blog_article_from_llm(cur, raw_id, blog_obj)
                    if article_id is None:
                        continue
                    conn.commit()
        except Exception as e:
            if "duplicate" in str(e).lower() or "unique" in str(e).lower():
                log_event(EVENT_DUPLICATE_ARTICLE, str(e), {"raw_article_id": str(raw_id)})
            else:
                log_event(EVENT_LLM_FAILURE, str(e), {"raw_article_id": str(raw_id), "stage": "insert_article"})
            logger.exception("Insert article failed for %s", raw_id)
            continue

        # --- Step 3: Action Protocol + Tracking Framework (sections 8 and 9) ---
        action_protocol_body = ""
        tracking_framework_body = ""
        ap_prompt_template = (
            ACTION_PROTOCOL_TRACKING_PROMPT_PATH.read_text()
            if ACTION_PROTOCOL_TRACKING_PROMPT_PATH.exists()
            else ""
        )
        ap_prompt = _load_prompt(
            ACTION_PROTOCOL_TRACKING_PROMPT_PATH,
            fallback=ap_prompt_template,
            title=title,
            summary=summary,
            key_findings=key_findings_str,
        )
        try:
            ap_response = generate_completion(ap_prompt)
            if isinstance(ap_response, dict):
                action_protocol_body = (ap_response.get("action_protocol") or "").strip()
                tracking_framework_body = (ap_response.get("tracking_framework") or "").strip()
            else:
                ap_obj = json.loads(ap_response) if isinstance(ap_response, str) else {}
                action_protocol_body = (ap_obj.get("action_protocol") or "").strip()
                tracking_framework_body = (ap_obj.get("tracking_framework") or "").strip()
            action_protocol_body = apply_medical_filter(action_protocol_body)
            tracking_framework_body = apply_medical_filter(tracking_framework_body)
        except Exception as e:
            log_event(
                EVENT_LLM_FAILURE,
                str(e),
                {"raw_article_id": str(raw_id), "stage": "action_protocol_tracking"},
            )
            logger.warning("Action protocol / tracking LLM failed for %s, article has 7 sections only", raw_id)
        else:
            try:
                with get_conn() as conn:
                    with conn.cursor() as cur:
                        _update_action_and_tracking_sections(
                            cur, article_id, action_protocol_body, tracking_framework_body
                        )
                        conn.commit()
                logger.info("Updated Action protocol and Tracking framework (sections 8–9) for article %s", article_id)
            except Exception as e:
                log_event(
                    EVENT_LLM_FAILURE,
                    str(e),
                    {"raw_article_id": str(raw_id), "stage": "insert_action_tracking_sections"},
                )
                logger.warning("Insert action/tracking sections failed for article %s: %s", article_id, e)

        with get_conn() as conn:
            with conn.cursor() as cur:
                cur.execute("UPDATE raw_medical_articles SET processed = true WHERE id = %s", (raw_id,))
                conn.commit()

        processed_count += 1
        logger.info("Processed raw_article %s -> blog article id %s", raw_id, article_id)

    return processed_count


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    limit = 10
    if len(sys.argv) > 1:
        try:
            limit = int(sys.argv[1])
        except ValueError:
            pass
    n = process_unprocessed_articles(limit=limit)
    print(f"Processed {n} articles.")
